package main

import (
	"bufio"
	"fmt"
	"go/ast"
	"go/token"
	"log"
	"os"

	pri "github.com/dlepex/typeinst/printer"
)

const preambleComment = "// This file was generated by typeinst. Do not edit, use `go generate` instead."

type astPrinter struct {
	pri.Config
	w    *bufio.Writer
	fset *token.FileSet
}

func newAstPrinter(w *bufio.Writer, rf pri.RenameFunc) *astPrinter {
	return &astPrinter{pri.Config{
		Mode:       pri.UseSpaces,
		RenameFunc: rf,
	}, w, token.NewFileSet()}
}

func (p *astPrinter) println(node interface{}) {
	err := p.Fprint(p.w, p.fset, node)
	if err != nil {
		log.Fatalf("Print AST error (%v) for node: %v", err, node)
	}
	_, err = p.w.WriteString("\n\n")
	if err != nil {
		log.Fatalf("Writer error: %v", err)
	}
}

func (im *Impl) Print() error {
	f, err := os.Create(im.outputFile)
	if err != nil {
		return err
	}
	defer f.Close()
	wr := bufio.NewWriter(f)
	defer wr.Flush()
	fmt.Fprintf(wr, "%s\npackage %s\n\n", preambleComment, im.pkgName)
	if !im.imports.IsEmpty() {
		newAstPrinter(wr, nil).println(im.imports.Decl())
	}
	typedefs := NewStrSet()
	for _, p := range im.pkg {
		p.print(wr, typedefs)
	}
	return nil
}

func (pk *PkgDesc) renameFunc(args *TypeArgs, inCtor bool) pri.RenameFunc {
	return func(id *ast.Ident) string {
		n := id.Name
		if pk.occTypes.Has(id) {
			t := pk.types[n]
			if t.typevar {
				return args.Binds[n]
			} else if t.IsGeneric() {
				return t.inst[args]
			} else {
				return n
			}
		}
		if inCtor {
			if pk.occCtors.Has(id) {
				t := pk.ctors[n]
				instName := t.inst[args]
				return MangleCtorName(n, t.name(), instName)
			}
		}
		if pk.occPkgs.Has(id) {
			return pk.impRename[n]
		}
		return n
	}
}

func (td *TypeDesc) Decl() *ast.GenDecl {
	gd := ast.GenDecl{}
	gd.Tok = token.TYPE
	// todo rename type in spec
	gd.Specs = []ast.Spec{td.spec}
	return &gd
}

func (pk *PkgDesc) print(wr *bufio.Writer, typedefs StrSet) {
	for _, tp := range pk.types {
		if !tp.visited {
			continue
		}
		if tp.IsGeneric() {
			for typeArgs, instName := range tp.inst {
				p := newAstPrinter(wr, pk.renameFunc(typeArgs, false))
				if !typedefs.Has(instName) {
					// instName is printed once (this is how "merged" types work)
					p.println(tp.Decl())
					typedefs.Add(instName)
				}
				if len(tp.ctors) > 0 {
					p := newAstPrinter(wr, pk.renameFunc(typeArgs, true))
					for _, f := range tp.ctors {
						p.println(f)
					}
				}
				for _, f := range tp.methods {
					p.println(f)
				}
			}
		}
	}
}
